// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using puma.Models;

#nullable disable

namespace puma.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20230126102156_new1")]
    partial class new1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("puma.Models.categoryMaster", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isdisabled")
                        .HasColumnType("bit");

                    b.Property<int?>("stationCategoryId")
                        .HasColumnType("int");

                    b.HasKey("categoryId");

                    b.HasIndex("stationCategoryId");

                    b.ToTable("categoryMaster");
                });

            modelBuilder.Entity("puma.Models.stationCategory", b =>
                {
                    b.Property<int>("stationCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stationCategoryId"));

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("stationCategoryId");

                    b.ToTable("stationCategories");
                });

            modelBuilder.Entity("puma.Models.stationMaster", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longtitude")
                        .HasColumnType("float");

                    b.Property<int?>("stationCategoryId")
                        .HasColumnType("int");

                    b.HasKey("StationId");

                    b.HasIndex("stationCategoryId");

                    b.ToTable("StationMasters");
                });

            modelBuilder.Entity("puma.Models.test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("puma.Models.categoryMaster", b =>
                {
                    b.HasOne("puma.Models.stationCategory", null)
                        .WithMany("categoryMasters")
                        .HasForeignKey("stationCategoryId");
                });

            modelBuilder.Entity("puma.Models.stationMaster", b =>
                {
                    b.HasOne("puma.Models.stationCategory", null)
                        .WithMany("stationMasters")
                        .HasForeignKey("stationCategoryId");
                });

            modelBuilder.Entity("puma.Models.stationCategory", b =>
                {
                    b.Navigation("categoryMasters");

                    b.Navigation("stationMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
